<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CustomerOrderManagement.Domain\CustomerOrderManagement.Domain.csproj" />
    <ProjectReference Include="..\CustomerOrderManagement.Business\CustomerOrderManagement.Business.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
